const express = require('express');
const router = express.Router();
const { addstudent, getstudent, deletestudent,updatestudent,login,changePassword } = require('../controllers/StudentController');
router.post('/addstudent', addstudent);
router.get('/getstudent', getstudent);
router.delete('/deletestudent/:studentId', deletestudent);
router.put("/updatestudent/:studentId", updatestudent);
router.post('/changePassword', changePassword);
router.post('/login',login);
module.exports = router;
